from .transcribe import NODE_CLASS_MAPPINGS as TRANSCRIBE_MAPPINGS
from .transcribe import NODE_DISPLAY_NAME_MAPPINGS as TRANSCRIBE_DISPLAY_MAPPINGS
from .aligner import NODE_CLASS_MAPPINGS as ALIGNER_MAPPINGS
from .aligner import NODE_DISPLAY_NAME_MAPPINGS as ALIGNER_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **TRANSCRIBE_MAPPINGS,
    **ALIGNER_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TRANSCRIBE_DISPLAY_MAPPINGS,
    **ALIGNER_DISPLAY_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
